name: ci

on: [push]

jobs:
  package-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run package build stretch
      run: script/cibuild-create-packages
    - name: Run package build focal
      run: script/cibuild-create-packages-focal
